VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ZtFieldProcedures"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
' Class ZtFieldProcedures.
' It contains Word.Field specific procedures.
' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *


' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
' Private variables.
Private pvtField As Word.Field
' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *


' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
' Friend procedures and properties.
Friend Sub Initialize(ByVal valField As Word.Field)
  
  Set pvtField = valField

End Sub

Friend Function GetCompleteRange() As Word.Range

  Dim locRange As Word.Range
  
  Set locRange = pvtField.Result
  locRange.SetRange pvtField.Code.Start - 1, locRange.End + 1
  
  Set GetCompleteRange = locRange

End Function

Friend Sub RemoveCodeFormat()
  
  Dim locRange As Range
  
  Set locRange = pvtField.Code
  With locRange
    .SetRange .Start - 1, .End
    .Style = wdStyleDefaultParagraphFont
  End With
  
  Set locRange = pvtField.Result
  With locRange
    .SetRange .End, .End + 1
    .Style = wdStyleDefaultParagraphFont
  End With

End Sub
' * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

